# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbour',
            name='occupants',
            field=models.IntegerField(null=True),
        ),
    ]
