# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_business_using'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Using',
            new_name='Profile',
        ),
    ]
