# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0007_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
