# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0009_auto_20181022_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(max_length=130, null=True),
        ),
    ]
