# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0012_auto_20181022_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbour',
            name='health_dept',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='neighbour',
            name='police_dept',
            field=models.IntegerField(null=True),
        ),
    ]
